### ISSUE TITLE
KeyError: 'no pem file for DEFAULT' when running Buildbot

### ISSUE THREAD

**Issue by adiroiban** [twisted-infra/braid#207]
I saw this in the logs

```
[buildbot.twistedmatrix.com] out: 2016-06-23T10:43:09+0000 [-]  step 'run-twistedchecker' complete: warnings
[buildbot.twistedmatrix.com] out: 2016-06-23T10:43:09+0000 [-]  <Build twistedchecker>: build finished
[buildbot.twistedmatrix.com] out: 2016-06-23T10:43:09+0000 [-] releaseLocks(<BuildSlave 'fedora-fedora22-2'>): []
[buildbot.twistedmatrix.com] out: 2016-06-23T10:43:09+0000 [twisted.python.log#info] "64.62.151.232" - - [23/Jun/2016:10:43:09 +0000] "POST /sysinfo.php HTTP/1.1" 302 - "-" "Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.8.1.12) Gecko/20080214 Firefox/2.0.0.12"
[buildbot.twistedmatrix.com] out: 2016-06-23T10:43:09+0000 [stderr#error] From cffi callback <function selectContext at 0x7f085c0f8de8>:
[buildbot.twistedmatrix.com] out: 2016-06-23T10:43:09+0000 [stderr#error] Traceback (most recent call last):
[buildbot.twistedmatrix.com] out: 2016-06-23T10:43:09+0000 [stderr#error]   File "/srv/bb-master/virtualenv/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1004, in wrapper
[buildbot.twistedmatrix.com] out: 2016-06-23T10:43:09+0000 [stderr#error]     callback(Connection._reverse_mapping[ssl])
[buildbot.twistedmatrix.com] out: 2016-06-23T10:43:09+0000 [stderr#error]   File "/srv/bb-master/virtualenv/local/lib/python2.7/site-packages/txsni/snimap.py", line 23, in selectContext
[buildbot.twistedmatrix.com] out: 2016-06-23T10:43:09+0000 [stderr#error]     self.mapping[connection.get_servername()]
[buildbot.twistedmatrix.com] out: 2016-06-23T10:43:09+0000 [stderr#error]   File "/srv/bb-master/virtualenv/local/lib/python2.7/site-packages/txacme/challenges.py", line 32, in __getitem__
[buildbot.twistedmatrix.com] out: 2016-06-23T10:43:09+0000 [stderr#error]     return self.underlay[key]
[buildbot.twistedmatrix.com] out: 2016-06-23T10:43:09+0000 [stderr#error]   File "/srv/bb-master/virtualenv/local/lib/python2.7/site-packages/txsni/snimap.py", line 41, in __getitem__
[buildbot.twistedmatrix.com] out: 2016-06-23T10:43:09+0000 [stderr#error]     raise KeyError("no pem file for " + hostname)
[buildbot.twistedmatrix.com] out: 2016-06-23T10:43:09+0000 [stderr#error] KeyError: 'no pem file for DEFAULT'
[buildbot.twistedmatrix.com] out: 2016-06-23T10:43:17+0000 [KeepaliveBroker,6,72.93.100.146] <RemoteShellCommand '['python', '-m', 'pip', 'install', 'pyopenssl', 'service_identity', 'zope.interface', 'idna', 'pyasn1', 'pyserial', 'python-subunit', 'constantly', 'appdirs', 'h2', 'priority', 'pycrypto', 'soappy', 'cffi', 'pypiwin32']'> rc=0

```

not sure if this is an upstream bug or some bug caused by bad configuration in braid

**Comment by tomprince** [comment]
This is definitely local configuration, related to HTTPS support.
