### ISSUE TITLE
PyPy 2.2 and pip don't work together

### ISSUE THREAD

**Issue by exarkun** [twisted-infra/braid#55]
[54.197.39.32] out: Exception:
[54.197.39.32] out: Traceback (most recent call last):
[54.197.39.32] out:   File "/opt/pypy-2.2-linux64/site-packages/pip/basecommand.py", line 122, in main
[54.197.39.32] out:     status = self.run(options, args)
[54.197.39.32] out:   File "/opt/pypy-2.2-linux64/site-packages/pip/commands/install.py", line 270, in run
[54.197.39.32] out:     requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
[54.197.39.32] out:   File "/opt/pypy-2.2-linux64/site-packages/pip/req.py", line 1164, in prepare_files
[54.197.39.32] out:     self.unpack_url(url, location, self.is_download)
[54.197.39.32] out:   File "/opt/pypy-2.2-linux64/site-packages/pip/req.py", line 1311, in unpack_url
[54.197.39.32] out:     retval = unpack_http_url(link, location, self.download_cache, self.download_dir, self.session)
[54.197.39.32] out:   File "/opt/pypy-2.2-linux64/site-packages/pip/download.py", line 533, in unpack_http_url
[54.197.39.32] out:     resp = session.get(target_url, stream=True)
[54.197.39.32] out:   File "/opt/pypy-2.2-linux64/site-packages/pip/_vendor/requests/sessions.py", line 394, in get
[54.197.39.32] out:     return self.request('GET', url, **kwargs)
[54.197.39.32] out:   File "/opt/pypy-2.2-linux64/site-packages/pip/download.py", line 236, in request
[54.197.39.32] out:     return super(PipSession, self).request(method, url, *args, **kwargs)
[54.197.39.32] out:   File "/opt/pypy-2.2-linux64/site-packages/pip/_vendor/requests/sessions.py", line 382, in request
[54.197.39.32] out:     resp = self.send(prep, **send_kwargs)
[54.197.39.32] out:   File "/opt/pypy-2.2-linux64/site-packages/pip/_vendor/requests/sessions.py", line 485, in send
[54.197.39.32] out:     r = adapter.send(request, **kwargs)
[54.197.39.32] out:   File "/opt/pypy-2.2-linux64/site-packages/pip/_vendor/requests/adapters.py", line 372, in send
[54.197.39.32] out:     raise ConnectionError(e)
[54.197.39.32] out: ConnectionError: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /packages/source/z/zope.interface/zope.interface-4.0.5.zip (Caused by <class '_socket.error'>: [Errno 9] Bad file descriptor)
[54.197.39.32] out: 
[54.197.39.32] out: Storing debug log for failure in /home/ubuntu/.pip/pip.log

Alex Gaynor suggests upgrading to PyPy 2.2.1.

**Comment by adiroiban** [comment]
I think that this should be fixed by #89
